mon_projet/mon_application/urls.py
from django.urls import path
from . import views

app_name = 'mon_application' 
urlpatterns = [
    path('activity_list/', views.activity_list, name='activity_list'),  # URL pour voir la liste des activités
    path('add_activity/', views.add_activity, name='add_activity'),      # URL pour ajouter une activité
    path('edit_activity/<int:pk>/', views.edit_activity, name='edit_activity'),  # URL pour éditer une activité
    path('delete_activity/<int:pk>/', views.delete_activity, name='delete_activity'),  # URL pour supprimer une activité
    path('statistics/', views.statistics_view, name='statistics_view'),  # URL pour voir les statistiques
    path('update_objectives/', views.update_objectives, name='update_objectives'),  # URL pour mettre à jour les objectifs
    path('objectifs/', views.user_objectives_view, name='user_objectives'),  # URL pour voir les objectifs
    
    # Routes API - Conservez le préfixe /api pour ces routes
    path('api/activities/', views.activity_list_api, name='activity_list_api'),  # URL API pour la liste des activités
    path('api/user_objective/', views.user_objective_api, name='user_objective_api'),  # URL API pour les objectifs utilisateur

    # Routes ajax 
     path('ajouter-activite-ajax/', views.ajouter_activite_ajax, name='ajouter_activite_ajax'),  # URL API pour la liste des activités
]

mon_projet/mon_projet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('', views.accueil, name="accueil"),
    path('admin/', admin.site.urls),
    path('utilisateur/', include('utilisateur.urls')),
    
    # Routes pour les API de token
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Ne pas conserver le préfixe /api pour ces routes
    path('activities/', include('mon_application.urls')),
    path('mon_application/', include('mon_application.urls')),
     
]

mon_projet/mon_application/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.

class Activity(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE) 
    date = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=100)
    marche = models.FloatField(default=0)
    jogging = models.FloatField(default=0)
    velo = models.FloatField(default=0)
    total = models.FloatField(default=0, editable=False)
    calories = models.FloatField(default=0, editable=False)
    vitesse = models.FloatField(default=0, editable=False) 
    

    def save(self, *args, **kwargs):
        self.total = self.marche + self.jogging + self.velo
        self.calories = (self.marche * 50) + (self.jogging * 70) + (self.velo * 35)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.date} - Total: {self.total} km, Calories: {self.calories} kcal"


class UserObjective(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    objectif_marche = models.FloatField(default=0)  # Défaut à zéro
    objectif_jogging = models.FloatField(default=0)  # Défaut à zéro
    objectif_velo = models.FloatField(default=0)  # Défaut à zéro

    def __str__(self):
        return f"Objectifs de {self.user.username}"

mon_projet/mon_application/forms.py
from django import forms
from .models import Activity
from .models import UserObjective


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['date', 'name', 'marche', 'jogging', 'velo']
        widgets = {
            'date': forms.DateTimeInput(attrs={
                'type': 'datetime-local',  # Utilise le type datetime-local pour date et heure
                
            }),
        }
class UserObjectiveForm(forms.ModelForm):
    class Meta:
        model = UserObjective
        fields = ['objectif_marche', 'objectif_jogging', 'objectif_velo']

mon_projet/mon_application/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ActivityForm
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from .models import UserObjective, Activity
from .forms import UserObjectiveForm
from django.contrib.auth.forms import UserCreationForm
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from .serializers import ActivitySerializer, UserObjectiveSerializer
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from django.http import JsonResponse
import json


# from django.http import HttpResponse
def accueil_view(request):
    activities = Activity.objects.all()  # Récupère toutes les activités

    # Récupérer les objectifs de l'utilisateur
    try:
        user_objective = UserObjective.objects.get(user=request.user)
    except UserObjective.DoesNotExist:
        user_objective = UserObjective(objectif_marche=10, objectif_jogging=5, objectif_velo=20)

    # Totaux
    total_marche = Activity.objects.aggregate(Sum('marche'))['marche__sum'] or 0
    total_jogging = Activity.objects.aggregate(Sum('jogging'))['jogging__sum'] or 0
    total_velo = Activity.objects.aggregate(Sum('velo'))['velo__sum'] or 0
    total_calories = Activity.objects.aggregate(Sum('calories'))['calories__sum'] or 0

    # Calcul du total des kilomètres effectués
    total_kilometres = total_marche + total_jogging + total_velo

    context = {
        'activities': activities,
        'user_objective': user_objective,
        'total_marche': total_marche,
        'total_jogging': total_jogging,
        'total_velo': total_velo,
        'total_calories': total_calories,
        'total_kilometres': total_kilometres,  # Vérifie que cette ligne est présente
    }
    
    return render(request, 'mon_application/accueil.html', context)

def contact(request):
    return render(request, 'contact.html')



@login_required
def ajouter_activite_ajax(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            
            # Crée une nouvelle activité
            activity = Activity.objects.create(
                user=request.user,
                name=data['activityType'],
                marche=float(data['marche']) if data['activityType'] == 'marche' else 0.0,
                jogging=float(data['jogging']) if data['activityType'] == 'jogging' else 0.0,
                velo=float(data['velo']) if data['activityType'] == 'velo' else 0.0,
                total=float(data['totalDistance']),
                calories=float(data['caloriesBurned']),
            )
            
            return JsonResponse({'status': 'Activity saved successfully', 'activity_id': activity.id})
        except KeyError as e:
            return JsonResponse({'error': f'Missing key: {str(e)}'}, status=400)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    
    return JsonResponse({'error': 'Invalid request'}, status=400)

@login_required
def activity_list(request):
    if request.user.is_authenticated:
        activities = Activity.objects.filter(user=request.user)
    else:
        activities = []
    return render(request, 'activity_list.html', {'activities': activities})

@login_required
def add_activity(request):
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            activity = form.save(commit=False)  # Ne pas enregistrer tout de suite
            activity.user = request.user  # Si tu as besoin d'associer un utilisateur
            activity.save()  # Enregistre l'activité et calcule total et calories
            return redirect('mon_application:activity_list')
    else:
        form = ActivityForm()
    
    return render(request, 'add_activity.html', {'form': form})

@login_required
def edit_activity(request, pk):
    activity = get_object_or_404(Activity, pk=pk)
    if request.method == 'POST':
        form = ActivityForm(request.POST, instance=activity)
        if form.is_valid():
            form.save()
            return redirect('mon_application:activity_list')
    else:
        form = ActivityForm(instance=activity)
    
    return render(request, 'edit_activity.html', {'form': form, 'activity': activity})
@login_required
def delete_activity(request, pk):

    activity = get_object_or_404(Activity, pk=pk)
    if request.method == 'POST':
        activity.delete()
        # Redirection vers la liste des activités
        return redirect('mon_application:activity_list')  # Redirection correcte vers l'URL
    return render(request, 'confirm_delete.html', {'activity': activity})  # Le bon template pour la confirmation

@login_required
def statistics_view(request):
    # Objectifs
    try:
        user_objective = UserObjective.objects.get(user=request.user)
    except UserObjective.DoesNotExist:
        user_objective = UserObjective(objectif_marche=10, objectif_jogging=5, objectif_velo=20)

    # Filtrer les activités pour l'utilisateur connecté
    user_activities = Activity.objects.filter(user=request.user)

    # Totaux
    total_marche = user_activities.aggregate(Sum('marche'))['marche__sum'] or 0
    total_jogging = user_activities.aggregate(Sum('jogging'))['jogging__sum'] or 0
    total_velo = user_activities.aggregate(Sum('velo'))['velo__sum'] or 0
    total_calories = user_activities.aggregate(Sum('calories'))['calories__sum'] or 0
    total_kilometres = total_marche + total_jogging + total_velo
    # Dernier enregistrement
    dernier_encodage = user_activities.last()
    distance_marche_derniere = dernier_encodage.marche if dernier_encodage else 0
    distance_jogging_derniere = dernier_encodage.jogging if dernier_encodage else 0
    distance_velo_derniere = dernier_encodage.velo if dernier_encodage else 0

    # Préparation des données pour le graphique
    labels = [activity.date.strftime('%Y-%m-%d') for activity in user_activities]  # Assurez-vous d'utiliser le bon champ de date
    marche_data = [activity.marche for activity in user_activities]
    jogging_data = [activity.jogging for activity in user_activities]
    velo_data = [activity.velo for activity in user_activities]
    calories_data = [activity.calories for activity in user_activities]

    # Calcul des totaux par date
    total_data = [m + j + v for m, j, v in zip(marche_data, jogging_data, velo_data)]

    context = {
        'total_marche': total_marche,
        'total_jogging': total_jogging,
        'total_velo': total_velo,
        'total_calories': total_calories,
        'total_kilometres': total_kilometres,  
        'distance_marche_derniere': distance_marche_derniere,
        'distance_jogging_derniere': distance_jogging_derniere,
        'distance_velo_derniere': distance_velo_derniere,
        'user_objective': user_objective,
        'labels': labels,  # Les dates pour le graphique
        'marche_data': marche_data,  # Données de marche
        'jogging_data': jogging_data,  # Données de jogging
        'velo_data': velo_data,  # Données de vélo
        'total_data': total_data,  # Données totales
        'calories_data': calories_data,  # Données de calories
    }

    return render(request, 'statistics_view.html', context)



@login_required
def update_objectives(request):
    try:
        objectives = UserObjective.objects.get(user=request.user)
    except UserObjective.DoesNotExist:
        objectives = UserObjective(user=request.user)

    if request.method == 'POST':
        form = UserObjectiveForm(request.POST, instance=objectives)
        if form.is_valid():
            form.save()
            return redirect('statistics_view')
    else:
        form = UserObjectiveForm(instance=objectives)

    return render(request, 'accueil.html', {'form': form})




@login_required
def user_objectives_view(request):
    # Récupérer ou créer les objectifs de l'utilisateur connecté avec des valeurs par défaut à zéro
    user_objective, created = UserObjective.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = UserObjectiveForm(request.POST, instance=user_objective)
        if form.is_valid():
            form.save()
            return redirect('mon_application:user_objectives')  # Redirection après modification
    else:
        form = UserObjectiveForm(instance=user_objective)

    context = {
        'form': form,
        'user_objective': user_objective,
    }
    return render(request, 'user_objectives.html', context)

@api_view(['GET', 'POST'])
@permission_classes([IsAuthenticated])
def activity_list_api(request):
    if request.method == 'GET':
        activities = Activity.objects.all()
        serializer = ActivitySerializer(activities, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = ActivitySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user)  # Associe l'utilisateur connecté
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET'])
def user_objective_api(request):
    try:
        user_objective = UserObjective.objects.get(user=request.user)
    except UserObjective.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = UserObjectiveSerializer(user_objective)
    return Response(serializer.data)

mon_projet/mon_application/templates/accueil.html
{% extends 'base.html' %}
{% block title %}Accueil{% endblock %}
{% load static %}
{% block content %}



    {% if user.is_authenticated %}    
    <h1>Application de Suivi d'Activités</h1>
    <nav class="navigation_activites_objectifs_statistiques">
        <ul>
            <li><a href="{% url 'mon_application:activity_list' %}">Mes activités</a></li>
            <li><a href="{% url 'mon_application:user_objectives' %}">Mes Objectifs</a></li>
            <li><a href="{% url 'mon_application:statistics_view' %}">Mes statistiques</a></li>
        </ul>
    </nav>
    <img class="img-accueil" src="{% static 'images/img-accueil.jpg' %}" alt="Logo">

    
    {% else %}    
    <h1>Application de Suivi d'Activités</h1>    
    <img class="img-accueil" src="{% static 'images/img-accueil.jpg' %}" alt="Logo">
    {% endif %}

{% endblock %}

mon_projet/mon_application/templates/activity_list.html
{% extends 'base.html' %}
{% block title %} Liste des Activités {% endblock %}
{% load static %}
{% block content %}
<nav class="navigation_activites_objectifs_statistiques">
    <ul>
        <li><a href="{% url 'mon_application:activity_list' %}">Mes activités</a></li>
        <li><a href="{% url 'mon_application:user_objectives' %}">Mes Objectifs</a></li>
        <li><a href="{% url 'mon_application:statistics_view' %}">Mes statistiques</a></li>
    </ul>
</nav>

<div class="entete_liste_activites">
    
    <a href="{% url 'mon_application:add_activity' %}" class="btn-entete-1">Ajouter une activité</a>
</div>


<div id="map"></div>
<!-- Sélecteur pour choisir l'activité -->
<select id="activityType">
    <option value="marche">Marche</option>
    <option value="jogging">Jogging</option>
    <option value="velo">Vélo</option>
</select>

<button id="startActivity">Démarrer l'activité</button>
<button id="stopActivity" disabled>Stopper l'activité</button>

<p>Distance parcourue : <span id="distance">0</span> km</p>
<p>Temps écoulé : <span id="chrono">00:00:00</span></p>
<p>Vitesse : <span id="speed">0</span> km/h</p>
<p>Calories dépensées : <span id="calories">0</span> kcal</p>
<script src="{% static 'javascript/activity_tracking.js' %}"></script>
<script src="{% static 'javascript/leaflet_geolocation.js' %}"></script>

<div class="activity-container">
    <div class="activity-row">
        {% if activities %}
        {% for activity in activities %}
        <div class="activity-card">
            <div class="activity-card-body">

                <p class="activity-card-text-date">Activité du {{ activity.date|date:"d F Y H:i" }}</p>
                <p class="activity-card-text">Description: {{ activity.name }}</p>
                <p class="activity-card-text">Marche : {{ activity.marche }} km</p>
                <p class="activity-card-text">Jogging : {{ activity.jogging }} km</p>
                <p class="activity-card-text">Vélo : {{ activity.velo }} km</p>
                <p class="activity-card-text">Total : {{ activity.total }} km</p>
                <p class="activity-card-text">Calories brûlées : {{ activity.calories }} kcal</p>

                <div class="activity-actions">
                    <a href="{% url 'mon_application:edit_activity' activity.pk %}"
                        class="btn-modifier-activite">Modifier</a>

                    <a href="{% url 'mon_application:delete_activity' activity.pk %}" class="btn-supprimer-activite"
                        onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette activité ?');">Supprimer</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>Aucune activité enregistrée.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

mon_projet/mon_application/templates/add_activity.html
{% extends 'base.html' %}


{% block title %} Ajouter Activité {% endblock %}

{% block content %}
<div class="container">
    <h1>Ajouter les données de la journée :</h1>
    <form id="activity-form" method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        {% if form.errors %}
            <div class="errors">
                <ul>
                    {% for field in form %}
                        {% if field.errors %}
                            <li>{{ field.label }}: {{ field.errors }}</li>
                        {% endif %} 
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        
        <button type="submit" class="btn btn-primary">Ajouter activité</button>
    </form>

    
    <a href="{% url 'mon_application:activity_list' %}" class="btn btn-secondary">Retour sur la liste des activités</a>
</div>
{% endblock %}

mon_projet/mon_application/templates/confirm_delete.html
{% extends 'base.html' %}
{% block title %}Confirmer la suppression{% endblock %}

{% block content %}
<h1>Confirmer la suppression</h1>
<p>Êtes-vous sûr de vouloir supprimer l'activité : {{ activity.name }} ?</p>

<form method="post">
    {% csrf_token %}    
    <button type="submit" class="btn btn-danger">Confirmer</button>
    <a href="{% url 'mon_application:activity_list' %}" class="btn btn-secondary">Annuler</a>
</form>
{% endblock %}

mon_projet/mon_application/templates/connexion.html
{% extends 'base.html' %}
{% block title %} Connexion {% endblock %}

{% block content %}
<div class="connexion-container">
    <h1 class="connexion-title">Connexion</h1>
    <form method="POST" class="connexion-form">
        {% csrf_token %}
        {% for field in form %}
            <div class="connexion-form-group">
                <label class="connexion-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% if field.errors %}
                    <div class="connexion-error">
                        {{ field.errors }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="connexion-button">Se connecter</button>
    </form>
</div>
{% endblock %}

mon_projet/mon_application/templates/contact.html
{% extends 'base.html' %}
{% block title %} Contact {% endblock %}

{% block content %}
<div class="contact-container">
    <h1>Contactez-nous</h1>
    <p>Si vous avez des questions ou des commentaires, <br> n'hésitez pas à nous contacter en utilisant le formulaire ci-dessous.</p>

    <form class="form-contact" method="post" action="{% url 'contact' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Nom</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>
        <div class="form-group">
            <label for="subject">Sujet</label>
            <input type="text" class="form-control" id="subject" name="subject" required>
        </div>
        <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>

    <hr>

    <h2>Informations de contact</h2>
    <p>Adresse : 123 Rue de l'Exemple, 75000 Paris, France</p>
    <p>Téléphone : +33 1 23 45 67 89</p>
    <p>Email : contact@example.com</p>
</div>
{% endblock %}

mon_projet/mon_application/templates/delete_activity.html
{% extends 'base.html' %}
{% block title %} Supprimer Activité {% endblock %}

{% block content %}
<div class="container">
    <h1>Êtes-vous sûr de vouloir supprimer l'activité ?</h1>
    
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmer</button>
        <a href="{% url 'mon_application:activity_list' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>
{% endblock %}

mon_projet/mon_application/templates/edit_activity.html
{% extends 'base.html' %}
{% block title %} {% if form.instance.pk %} Modifier Activité {% else %} Ajouter Activité {% endif %} {% endblock %}

{% block content %}
<div class="container">
    <h1>{% if form.instance.pk %}Modifier{% else %}Ajouter{% endif %} une activité</h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">
            {% if form.instance.pk %} Sauver les modifications {% else %} Ajouter activité {% endif %}
        </button>
    </form>

    <a href="{% url 'mon_application:activity_list' %}" class="btn btn-secondary">Retour vers la liste</a>
</div>
{% endblock %}

mon_projet/mon_application/templates/inscription.html
{% extends 'base.html' %}
{% block title %} Inscription {% endblock %}

{% block content %}
<div class="inscription-container">
    <h1 class="inscription-title">Inscription</h1>
    <form method="POST" class="inscription-form">
        {% csrf_token %}
        {% for field in form %}
            <div class="inscription-form-group">
                <label class="inscription-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% if field.errors %}
                    <div class="inscription-error">
                        {{ field.errors }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="inscription-button">S'inscrire</button>
    </form>
</div>

{% endblock %}

mon_projet/mon_application/templates/statistics_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Statistiques{% endblock %}

{% block content %}

<nav class="navigation_activites_objectifs_statistiques">
    <ul>
        <li><a href="{% url 'mon_application:activity_list' %}">Mes activités</a></li>
        <li><a href="{% url 'mon_application:user_objectives' %}">Mes Objectifs</a></li>
        <li><a href="{% url 'mon_application:statistics_view' %}">Mes statistiques</a></li>
    </ul>
</nav>

<h1>Statistiques Globales</h1>

<div class="statistics-section">
    <h2>Total des kilomètres</h2>
    <p>Total des kilomètres en marche : {{ total_marche }} km</p>
    <p>Total des kilomètres en jogging : {{ total_jogging }} km</p>
    <p>Total des kilomètres en vélo : {{ total_velo }} km</p>
    <p>Total des kilomètres effectués : {{ total_kilometres|floatformat:2 }} km</p>

    <h2>Calories Brûlées</h2>
    <p>Total des calories brûlées : {{ total_calories|floatformat:2 }} kcal</p>

    <h2>Objectifs</h2>
    <p>Objectif de marche : {{ user_objective.objectif_marche }} km</p>
    <p>Objectif de jogging : {{ user_objective.objectif_jogging }} km</p>
    <p>Objectif de vélo : {{ user_objective.objectif_velo }} km</p>
    <div class="graphique">
        <!-- Ajouter le canvas pour le graphique -->
        <canvas id="activityChart"></canvas>
    </div>
</div>

<a href="{% url 'mon_application:activity_list' %}" class="btn btn-primary">Retour aux activités</a>

<!-- Inclure Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<!-- Passer les données à JavaScript -->
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const labels = {{ labels|safe }};  // Dates
        const marcheData = {{ marche_data|safe }};  // Données de marche
        const joggingData = {{ jogging_data|safe }};  // Données de jogging
        const veloData = {{ velo_data|safe }};  // Données de vélo
        const totalData = {{ total_data|safe }};  // Données totales
        const caloriesData = {{ calories_data|safe }};  // Données de calories
        
        updateChart(labels, marcheData, joggingData, veloData, totalData, caloriesData);
    });
</script>
<!-- Inclure ton fichier JavaScript -->
<script src="{% static 'javascript/chart.js' %}"></script>

{% endblock %}

mon_projet/mon_application/templates/update_objectives.html
{% extends 'base.html' %}
{% block title %} Mettre à jour les Objectifs {% endblock %}

{% block content %}
<div class="container">
    <h1>Mettre à jour vos objectifs</h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Sauvegarder les objectifs</button>
    </form>
</div>
{% endblock %}

mon_projet/mon_application/templates/user_objectives.html
{% extends 'base.html' %}
{% block title %} Objectifs {% endblock %}
{% load static %}
{% block content %}

<nav class="navigation_activites_objectifs_statistiques">
    <ul>
        <li><a href="{% url 'mon_application:activity_list' %}">Mes activités</a></li>
        <li><a href="{% url 'mon_application:user_objectives' %}">Mes Objectifs</a></li>
        <li><a href="{% url 'mon_application:statistics_view' %}">Mes statistiques</a></li>
    </ul>
</nav>

<h1>Mes Objectifs</h1>

<form class="form-objectifs-user" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Mettre à jour les objectifs</button>
</form>
<div class="objectifs-actuels">
    <h2>Objectifs actuels</h2>
    <ul>
        <li>Marche : {{ user_objective.objectif_marche }} km</li>
        <li>Jogging : {{ user_objective.objectif_jogging }} km</li>
        <li>Vélo : {{ user_objective.objectif_velo }} km</li>
    </ul>
</div>
{% endblock %}